package services;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class DBManager {
	public static Connection createDatabaseConnection() throws SQLException {
		Connection conn = DriverManager
				.getConnection("jdbc:hsqldb:mem://localhost/mydatabase");

		Statement stmt = conn.createStatement();
		boolean customerTableExists = false;
		boolean movieTableExists = false;
		boolean itemTypeTableExists = false;

		ResultSet rs = conn.getMetaData().getTables(null, null, null, null);

		while (rs.next()) {
			if ("customer".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
				customerTableExists = true;
				break;
			}
			if ("item_type".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
				itemTypeTableExists = true;
				break;
			}
			if ("movie".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
				movieTableExists = true;
				break;
			}
		}

		if (!customerTableExists) {
			stmt.executeUpdate("" + "CREATE TABLE customer("
					+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
					+ "name varchar(20)," + "money DECIMAL)");
		}
		if (!itemTypeTableExists) {
			stmt.executeUpdate("" + "CREATE TABLE item_type("
					+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
					+ "name varchar(20))");
		}
		if (!movieTableExists) {
			stmt.executeUpdate("" + "CREATE TABLE movie("
					+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
					+ "director varchar(20)," + "title varchar(20),"
					+ "available BOOLEAN," + "item_type_id bigint,"
					+ "price DECIMAL," + "customer_id bigint,"
//					+ "FOREIGN KEY (item_type_id) REFERENCES item_type(id),"
					+ "FOREIGN KEY (customer_id) REFERENCES customer(id))");
		}
		
		return conn;
	}
}
